# Generated by Django 5.1.7 on 2025-04-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_dates', to='api.museum')),
            ],
        ),
    ]
