# Generated by Django 5.1.7 on 2025-04-23 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_closeddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closeddate',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='closeddate',
            name='date_to',
            field=models.DateField(default=datetime.date(2025, 4, 23)),
            preserve_default=False,
        ),
    ]
