# Generated by Django 5.1.7 on 2025-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_date_closeddate_date_from_closeddate_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
